version: 2.1
orbs:
  node: circleci/node@4.7.0
  codecov: codecov/codecov@3.2.0
jobs:
  build-job:
    docker:
      - image: node:11.10.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - run:
          name: build
          command: |
              touch .env
              echo "REACT_APP_REALM_APP_ID" > .env
              echo "REACT_APP_MONGO_CLIENT" > .env
              echo "REACT_APP_MONGODB_DB_NAME" > .env
              echo "REACT_APP_TMDB_KEY" > .env
              npm run build

      - save_cache:
          paths:
            - build
            - node_modules
            - package.json
            - firebase.json
            - .firebaserc
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

      # run tests!
      - run: npm run test

      - run: npm run test:coverage

      - codecov/upload:
          file: './coverage/clover.xml'

  deploy-job:
    docker:
      - image: node:11.10.1
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: show directory
          command: pwd
      - run:
          name: Install Firebase
          command: npm install -g firebase-tools@9.23.1
      - run:
          name: look in directory
          command: ls -ltr
      - run:
          name: use default firebase project
          command: firebase use default
      - run:
          name: Deploy Master to Firebase
          command: firebase deploy --only hosting --token ${FIREBASE_TOKEN}

workflows:
  version: 2

  -deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master