version: 2.1
orbs:
  node: circleci/node@4.7.0
  codecov: codecov/codecov@3.2.0
  firebase-deploy: azdevs/firebase-deploy@1.0.0
jobs:
  build:
    docker:
      - image: node:11.10.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build

      # run tests!
      - run: npm run test

      - run: npm run test:coverage

      - codecov/upload:
          file: './coverage/clover.xml'

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dist
            - firebase.json
            - .firebaserc
            - firestore.rules
            - firestore.indexes.json

      deploy-staging:
        docker:
          - image: node:11.10.1
        steps:
          - attach_workspace:
              at: /tmp/workspace
          - firebase-deploy/deploy:
              token: $FIREBASE_TOKEN
              alias: default
      workflows:
        version: 2
        build-and-deploy-staging:
          jobs:
            - build
            - deploy-staging:
                requires:
                  - build
                filters:
                  branches:
                    ignore: master