version: 2.1
orbs:
  node: circleci/node@4.7.0
  codecov: codecov/codecov@3.2.0
  firebase-deploy: azdevs/firebase-deploy@1.0.0
jobs:
  build-job:
    docker:
      - image: node:11.10.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - run: npm run build

      - save_cache:
          paths:
            - node_modules
            - package.json
            - firebase.json
            - .firebaserc
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

      # run tests!
      - run: npm run test

      - run: npm run test:coverage

      - codecov/upload:
          file: './coverage/clover.xml'

      - persist_to_workspace:
          root: ./
          paths:
            - public
            - .firebaserc
            - firebase.json

  deploy-job:
    docker:
      - image: node:11.10.1

    working_directory: ~/repo

    steps:
      - attach_workspace:
         at: ./

      - firebase-deploy/deploy:
         token: $FIREBASE_TOKEN

workflows:
  version: 2

  -deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master